name: GDG Garage
url: http://gdg-garage.github.io/gdg-garage-site
markdown: redcarpet
highlighter: pygments
encoding: UTF-8
safe: true
redcarpet:
  extensions: ['smart']
exclude: ['fetch_projects.dart', 'start_server.sh', 'push_to_github_pages.sh']
